{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "2bbed392-3063-43a3-b827-0f30ede12707",
   "metadata": {},
   "source": [
    "# Causal ML"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "1f14b98b-8b63-4e54-84af-22b50d3e7e01",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting causalml\n",
      "  Using cached causalml-0.12.3.tar.gz (406 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25hRequirement already satisfied: setuptools>=41.0.0 in /Users/jace/opt/anaconda3/envs/DL/causalml/lib/python3.10/site-packages (from causalml) (62.3.2)\n",
      "Requirement already satisfied: pip>=10.0 in /Users/jace/opt/anaconda3/envs/DL/causalml/lib/python3.10/site-packages (from causalml) (22.1.1)\n",
      "Collecting numpy>=1.18.5\n",
      "  Using cached numpy-1.22.4-cp310-cp310-macosx_11_0_arm64.whl (12.8 MB)\n",
      "Collecting scipy>=1.4.1\n",
      "  Using cached scipy-1.8.1-cp310-cp310-macosx_12_0_arm64.whl (28.7 MB)\n",
      "Collecting matplotlib\n",
      "  Using cached matplotlib-3.5.2-cp310-cp310-macosx_11_0_arm64.whl (7.2 MB)\n",
      "Collecting pandas>=0.24.1\n",
      "  Using cached pandas-1.4.2-cp310-cp310-macosx_11_0_arm64.whl (10.1 MB)\n",
      "Collecting scikit-learn>=0.22.0\n",
      "  Using cached scikit_learn-1.1.1-cp310-cp310-macosx_12_0_arm64.whl (7.7 MB)\n",
      "Collecting statsmodels>=0.9.0\n",
      "  Using cached statsmodels-0.13.2-cp310-cp310-macosx_11_0_arm64.whl (9.1 MB)\n",
      "Collecting seaborn\n",
      "  Using cached seaborn-0.11.2-py3-none-any.whl (292 kB)\n",
      "Collecting Cython>=0.28.0\n",
      "  Using cached Cython-0.29.30-py2.py3-none-any.whl (985 kB)\n",
      "Collecting xgboost\n",
      "  Using cached xgboost-1.6.1-py3-none-macosx_12_0_arm64.whl (1.5 MB)\n",
      "Collecting pydotplus\n",
      "  Using cached pydotplus-2.0.2.tar.gz (278 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25hCollecting tqdm\n",
      "  Using cached tqdm-4.64.0-py2.py3-none-any.whl (78 kB)\n",
      "Collecting shap\n",
      "  Using cached shap-0.40.0-cp310-cp310-macosx_11_0_arm64.whl\n",
      "Collecting dill\n",
      "  Using cached dill-0.3.5.1-py2.py3-none-any.whl (95 kB)\n",
      "Collecting lightgbm\n",
      "  Using cached lightgbm-3.3.2-py3-none-any.whl\n",
      "Collecting pygam\n",
      "  Using cached pygam-0.8.0-py2.py3-none-any.whl (1.8 MB)\n",
      "Requirement already satisfied: packaging in /Users/jace/opt/anaconda3/envs/DL/causalml/lib/python3.10/site-packages (from causalml) (21.3)\n",
      "Collecting torch\n",
      "  Downloading torch-1.11.0-cp310-none-macosx_11_0_arm64.whl (43.1 MB)\n",
      "\u001b[2K     \u001b[38;2;114;156;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m43.1/43.1 MB\u001b[0m \u001b[31m1.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0mm eta \u001b[36m0:00:01\u001b[0m[36m0:00:01\u001b[0m\n",
      "\u001b[?25hCollecting pyro-ppl\n",
      "  Using cached pyro_ppl-1.8.1-py3-none-any.whl (718 kB)\n",
      "Collecting graphviz\n",
      "  Using cached graphviz-0.20-py3-none-any.whl (46 kB)\n",
      "Requirement already satisfied: pytz>=2020.1 in /Users/jace/opt/anaconda3/envs/DL/causalml/lib/python3.10/site-packages (from pandas>=0.24.1->causalml) (2022.1)\n",
      "Requirement already satisfied: python-dateutil>=2.8.1 in /Users/jace/opt/anaconda3/envs/DL/causalml/lib/python3.10/site-packages (from pandas>=0.24.1->causalml) (2.8.2)\n",
      "Collecting threadpoolctl>=2.0.0\n",
      "  Using cached threadpoolctl-3.1.0-py3-none-any.whl (14 kB)\n",
      "Collecting joblib>=1.0.0\n",
      "  Using cached joblib-1.1.0-py2.py3-none-any.whl (306 kB)\n",
      "Collecting patsy>=0.5.2\n",
      "  Using cached patsy-0.5.2-py2.py3-none-any.whl (233 kB)\n",
      "Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /Users/jace/opt/anaconda3/envs/DL/causalml/lib/python3.10/site-packages (from packaging->causalml) (3.0.9)\n",
      "Requirement already satisfied: wheel in /Users/jace/opt/anaconda3/envs/DL/causalml/lib/python3.10/site-packages (from lightgbm->causalml) (0.37.1)\n",
      "Collecting kiwisolver>=1.0.1\n",
      "  Using cached kiwisolver-1.4.2-cp310-cp310-macosx_11_0_arm64.whl (63 kB)\n",
      "Collecting fonttools>=4.22.0\n",
      "  Using cached fonttools-4.33.3-py3-none-any.whl (930 kB)\n",
      "Collecting cycler>=0.10\n",
      "  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)\n",
      "Collecting pillow>=6.2.0\n",
      "  Using cached Pillow-9.1.1-cp310-cp310-macosx_11_0_arm64.whl (2.8 MB)\n",
      "Collecting future\n",
      "  Using cached future-0.18.2.tar.gz (829 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25hCollecting progressbar2\n",
      "  Using cached progressbar2-4.0.0-py2.py3-none-any.whl (26 kB)\n",
      "Collecting opt-einsum>=2.3.2\n",
      "  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)\n",
      "Collecting pyro-api>=0.1.1\n",
      "  Using cached pyro_api-0.1.2-py3-none-any.whl (11 kB)\n",
      "Collecting typing-extensions\n",
      "  Using cached typing_extensions-4.2.0-py3-none-any.whl (24 kB)\n",
      "Collecting cloudpickle\n",
      "  Using cached cloudpickle-2.1.0-py3-none-any.whl (25 kB)\n",
      "Collecting numba\n",
      "  Using cached numba-0.55.2-cp310-cp310-macosx_11_0_arm64.whl (2.3 MB)\n",
      "Collecting slicer==0.0.7\n",
      "  Using cached slicer-0.0.7-py3-none-any.whl (14 kB)\n",
      "Requirement already satisfied: six in /Users/jace/opt/anaconda3/envs/DL/causalml/lib/python3.10/site-packages (from patsy>=0.5.2->statsmodels>=0.9.0->causalml) (1.16.0)\n",
      "Collecting llvmlite<0.39,>=0.38.0rc1\n",
      "  Using cached llvmlite-0.38.1-cp310-cp310-macosx_11_0_arm64.whl (23.1 MB)\n",
      "Collecting python-utils>=3.0.0\n",
      "  Using cached python_utils-3.3.1-py2.py3-none-any.whl (22 kB)\n",
      "Building wheels for collected packages: causalml, pydotplus, future\n",
      "  Building wheel for causalml (setup.py) ... \u001b[?25lerror\n",
      "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "  \n",
      "  \u001b[31m×\u001b[0m \u001b[32mpython setup.py bdist_wheel\u001b[0m did not run successfully.\n",
      "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "  \u001b[31m╰─>\u001b[0m \u001b[31m[33 lines of output]\u001b[0m\n",
      "  \u001b[31m   \u001b[0m /Users/jace/opt/anaconda3/envs/DL/causalml/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.\n",
      "  \u001b[31m   \u001b[0m   warnings.warn(\n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/vn/78yrfhs92slfj6nr61fhb9w00000gn/T/pip-install-kwbmvzdd/causalml_d42ece055c2d45bd91ed21dc74796834/setup.py\", line 13, in <module>\n",
      "  \u001b[31m   \u001b[0m     from numpy import get_include as np_get_include\n",
      "  \u001b[31m   \u001b[0m ModuleNotFoundError: No module named 'numpy'\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m During handling of the above exception, another exception occurred:\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 2, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"<pip-setuptools-caller>\", line 34, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/vn/78yrfhs92slfj6nr61fhb9w00000gn/T/pip-install-kwbmvzdd/causalml_d42ece055c2d45bd91ed21dc74796834/setup.py\", line 15, in <module>\n",
      "  \u001b[31m   \u001b[0m     dist.Distribution().fetch_build_eggs([\"numpy\"])\n",
      "  \u001b[31m   \u001b[0m   File \"/Users/jace/opt/anaconda3/envs/DL/causalml/lib/python3.10/site-packages/setuptools/dist.py\", line 876, in fetch_build_eggs\n",
      "  \u001b[31m   \u001b[0m     resolved_dists = pkg_resources.working_set.resolve(\n",
      "  \u001b[31m   \u001b[0m   File \"/Users/jace/opt/anaconda3/envs/DL/causalml/lib/python3.10/site-packages/pkg_resources/__init__.py\", line 789, in resolve\n",
      "  \u001b[31m   \u001b[0m     dist = best[req.key] = env.best_match(\n",
      "  \u001b[31m   \u001b[0m   File \"/Users/jace/opt/anaconda3/envs/DL/causalml/lib/python3.10/site-packages/pkg_resources/__init__.py\", line 1075, in best_match\n",
      "  \u001b[31m   \u001b[0m     return self.obtain(req, installer)\n",
      "  \u001b[31m   \u001b[0m   File \"/Users/jace/opt/anaconda3/envs/DL/causalml/lib/python3.10/site-packages/pkg_resources/__init__.py\", line 1087, in obtain\n",
      "  \u001b[31m   \u001b[0m     return installer(requirement)\n",
      "  \u001b[31m   \u001b[0m   File \"/Users/jace/opt/anaconda3/envs/DL/causalml/lib/python3.10/site-packages/setuptools/dist.py\", line 956, in fetch_build_egg\n",
      "  \u001b[31m   \u001b[0m     return fetch_build_egg(self, req)\n",
      "  \u001b[31m   \u001b[0m   File \"/Users/jace/opt/anaconda3/envs/DL/causalml/lib/python3.10/site-packages/setuptools/installer.py\", line 87, in fetch_build_egg\n",
      "  \u001b[31m   \u001b[0m     wheel.install_as_egg(dist_location)\n",
      "  \u001b[31m   \u001b[0m   File \"/Users/jace/opt/anaconda3/envs/DL/causalml/lib/python3.10/site-packages/setuptools/wheel.py\", line 96, in install_as_egg\n",
      "  \u001b[31m   \u001b[0m     self._install_as_egg(destination_eggdir, zf)\n",
      "  \u001b[31m   \u001b[0m   File \"/Users/jace/opt/anaconda3/envs/DL/causalml/lib/python3.10/site-packages/setuptools/wheel.py\", line 104, in _install_as_egg\n",
      "  \u001b[31m   \u001b[0m     self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)\n",
      "  \u001b[31m   \u001b[0m   File \"/Users/jace/opt/anaconda3/envs/DL/causalml/lib/python3.10/site-packages/setuptools/wheel.py\", line 148, in _convert_metadata\n",
      "  \u001b[31m   \u001b[0m     os.rename(dist_info, egg_info)\n",
      "  \u001b[31m   \u001b[0m OSError: [Errno 66] Directory not empty: '/private/var/folders/vn/78yrfhs92slfj6nr61fhb9w00000gn/T/pip-install-kwbmvzdd/causalml_d42ece055c2d45bd91ed21dc74796834/.eggs/numpy-1.22.4-py3.10-macosx-11.0-arm64.egg/numpy-1.22.4.dist-info' -> '/private/var/folders/vn/78yrfhs92slfj6nr61fhb9w00000gn/T/pip-install-kwbmvzdd/causalml_d42ece055c2d45bd91ed21dc74796834/.eggs/numpy-1.22.4-py3.10-macosx-11.0-arm64.egg/EGG-INFO'\n",
      "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n",
      "  \n",
      "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "\u001b[31m  ERROR: Failed building wheel for causalml\u001b[0m\u001b[31m\n",
      "\u001b[0m\u001b[?25h  Running setup.py clean for causalml\n",
      "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "  \n",
      "  \u001b[31m×\u001b[0m \u001b[32mpython setup.py clean\u001b[0m did not run successfully.\n",
      "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "  \u001b[31m╰─>\u001b[0m \u001b[31m[33 lines of output]\u001b[0m\n",
      "  \u001b[31m   \u001b[0m /Users/jace/opt/anaconda3/envs/DL/causalml/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.\n",
      "  \u001b[31m   \u001b[0m   warnings.warn(\n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/vn/78yrfhs92slfj6nr61fhb9w00000gn/T/pip-install-kwbmvzdd/causalml_d42ece055c2d45bd91ed21dc74796834/setup.py\", line 13, in <module>\n",
      "  \u001b[31m   \u001b[0m     from numpy import get_include as np_get_include\n",
      "  \u001b[31m   \u001b[0m ModuleNotFoundError: No module named 'numpy'\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m During handling of the above exception, another exception occurred:\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 2, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"<pip-setuptools-caller>\", line 34, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/vn/78yrfhs92slfj6nr61fhb9w00000gn/T/pip-install-kwbmvzdd/causalml_d42ece055c2d45bd91ed21dc74796834/setup.py\", line 15, in <module>\n",
      "  \u001b[31m   \u001b[0m     dist.Distribution().fetch_build_eggs([\"numpy\"])\n",
      "  \u001b[31m   \u001b[0m   File \"/Users/jace/opt/anaconda3/envs/DL/causalml/lib/python3.10/site-packages/setuptools/dist.py\", line 876, in fetch_build_eggs\n",
      "  \u001b[31m   \u001b[0m     resolved_dists = pkg_resources.working_set.resolve(\n",
      "  \u001b[31m   \u001b[0m   File \"/Users/jace/opt/anaconda3/envs/DL/causalml/lib/python3.10/site-packages/pkg_resources/__init__.py\", line 789, in resolve\n",
      "  \u001b[31m   \u001b[0m     dist = best[req.key] = env.best_match(\n",
      "  \u001b[31m   \u001b[0m   File \"/Users/jace/opt/anaconda3/envs/DL/causalml/lib/python3.10/site-packages/pkg_resources/__init__.py\", line 1075, in best_match\n",
      "  \u001b[31m   \u001b[0m     return self.obtain(req, installer)\n",
      "  \u001b[31m   \u001b[0m   File \"/Users/jace/opt/anaconda3/envs/DL/causalml/lib/python3.10/site-packages/pkg_resources/__init__.py\", line 1087, in obtain\n",
      "  \u001b[31m   \u001b[0m     return installer(requirement)\n",
      "  \u001b[31m   \u001b[0m   File \"/Users/jace/opt/anaconda3/envs/DL/causalml/lib/python3.10/site-packages/setuptools/dist.py\", line 956, in fetch_build_egg\n",
      "  \u001b[31m   \u001b[0m     return fetch_build_egg(self, req)\n",
      "  \u001b[31m   \u001b[0m   File \"/Users/jace/opt/anaconda3/envs/DL/causalml/lib/python3.10/site-packages/setuptools/installer.py\", line 87, in fetch_build_egg\n",
      "  \u001b[31m   \u001b[0m     wheel.install_as_egg(dist_location)\n",
      "  \u001b[31m   \u001b[0m   File \"/Users/jace/opt/anaconda3/envs/DL/causalml/lib/python3.10/site-packages/setuptools/wheel.py\", line 96, in install_as_egg\n",
      "  \u001b[31m   \u001b[0m     self._install_as_egg(destination_eggdir, zf)\n",
      "  \u001b[31m   \u001b[0m   File \"/Users/jace/opt/anaconda3/envs/DL/causalml/lib/python3.10/site-packages/setuptools/wheel.py\", line 104, in _install_as_egg\n",
      "  \u001b[31m   \u001b[0m     self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)\n",
      "  \u001b[31m   \u001b[0m   File \"/Users/jace/opt/anaconda3/envs/DL/causalml/lib/python3.10/site-packages/setuptools/wheel.py\", line 148, in _convert_metadata\n",
      "  \u001b[31m   \u001b[0m     os.rename(dist_info, egg_info)\n",
      "  \u001b[31m   \u001b[0m OSError: [Errno 66] Directory not empty: '/private/var/folders/vn/78yrfhs92slfj6nr61fhb9w00000gn/T/pip-install-kwbmvzdd/causalml_d42ece055c2d45bd91ed21dc74796834/.eggs/numpy-1.22.4-py3.10-macosx-11.0-arm64.egg/numpy-1.22.4.dist-info' -> '/private/var/folders/vn/78yrfhs92slfj6nr61fhb9w00000gn/T/pip-install-kwbmvzdd/causalml_d42ece055c2d45bd91ed21dc74796834/.eggs/numpy-1.22.4-py3.10-macosx-11.0-arm64.egg/EGG-INFO'\n",
      "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n",
      "  \n",
      "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "\u001b[31m  ERROR: Failed cleaning build dir for causalml\u001b[0m\u001b[31m\n",
      "\u001b[0m  Building wheel for pydotplus (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25h  Created wheel for pydotplus: filename=pydotplus-2.0.2-py3-none-any.whl size=24554 sha256=08d12c75d9f00e1bbfee80979d3343457e42bd21687c3703729fd3e715e6a715\n",
      "  Stored in directory: /Users/jace/Library/Caches/pip/wheels/69/b2/67/08f0eef649af92df772c09f451558298e07fab1bc7cdf33db0\n",
      "  Building wheel for future (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25h  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491058 sha256=a583a6c54091b23bf5c0b7d80b5bdd69bc909de5bbb992052b87564620b29596\n",
      "  Stored in directory: /Users/jace/Library/Caches/pip/wheels/22/73/06/557dc4f4ef68179b9d763930d6eec26b88ed7c389b19588a1c\n",
      "Successfully built pydotplus future\n",
      "Failed to build causalml\n",
      "Installing collected packages: pyro-api, typing-extensions, tqdm, threadpoolctl, slicer, python-utils, pydotplus, pillow, numpy, llvmlite, kiwisolver, joblib, graphviz, future, fonttools, dill, Cython, cycler, cloudpickle, torch, scipy, progressbar2, patsy, pandas, opt-einsum, numba, matplotlib, xgboost, statsmodels, seaborn, scikit-learn, pyro-ppl, pygam, shap, lightgbm, causalml\n",
      "  Running setup.py install for causalml ... \u001b[?25lerror\n",
      "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "  \n",
      "  \u001b[31m×\u001b[0m \u001b[32mRunning setup.py install for causalml\u001b[0m did not run successfully.\n",
      "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "  \u001b[31m╰─>\u001b[0m \u001b[31m[57 lines of output]\u001b[0m\n",
      "  \u001b[31m   \u001b[0m Compiling causalml/inference/tree/causaltree.pyx because it depends on /Users/jace/opt/anaconda3/envs/DL/causalml/lib/python3.10/site-packages/sklearn/tree/_criterion.pxd.\n",
      "  \u001b[31m   \u001b[0m Compiling causalml/inference/tree/uplift.pyx because it depends on /Users/jace/opt/anaconda3/envs/DL/causalml/lib/python3.10/site-packages/Cython/Includes/libc/string.pxd.\n",
      "  \u001b[31m   \u001b[0m [1/2] Cythonizing causalml/inference/tree/causaltree.pyx\n",
      "  \u001b[31m   \u001b[0m /Users/jace/opt/anaconda3/envs/DL/causalml/lib/python3.10/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /private/var/folders/vn/78yrfhs92slfj6nr61fhb9w00000gn/T/pip-install-kwbmvzdd/causalml_d42ece055c2d45bd91ed21dc74796834/causalml/inference/tree/causaltree.pyx\n",
      "  \u001b[31m   \u001b[0m   tree = Parsing.p_module(s, pxd, full_module_name)\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m Error compiling Cython file:\n",
      "  \u001b[31m   \u001b[0m ------------------------------------------------------------\n",
      "  \u001b[31m   \u001b[0m ...\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m     cdef double node_impurity(self) nogil:\n",
      "  \u001b[31m   \u001b[0m         \"\"\"Evaluate the impurity of the current node, i.e. the impurity of\n",
      "  \u001b[31m   \u001b[0m            samples[start:end].\"\"\"\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         cdef double* sum_total = self.sum_total\n",
      "  \u001b[31m   \u001b[0m                                     ^\n",
      "  \u001b[31m   \u001b[0m ------------------------------------------------------------\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m causalml/inference/tree/causaltree.pyx:77:37: Cannot assign type 'double[::1]' to 'double *'\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m Error compiling Cython file:\n",
      "  \u001b[31m   \u001b[0m ------------------------------------------------------------\n",
      "  \u001b[31m   \u001b[0m ...\n",
      "  \u001b[31m   \u001b[0m         cdef SIZE_t* samples = self.samples\n",
      "  \u001b[31m   \u001b[0m         cdef SIZE_t start = self.start\n",
      "  \u001b[31m   \u001b[0m         cdef SIZE_t pos = self.pos\n",
      "  \u001b[31m   \u001b[0m         cdef SIZE_t end = self.end\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         cdef double* sum_left = self.sum_left\n",
      "  \u001b[31m   \u001b[0m                                    ^\n",
      "  \u001b[31m   \u001b[0m ------------------------------------------------------------\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m causalml/inference/tree/causaltree.pyx:135:36: Cannot assign type 'double[::1]' to 'double *'\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m Error compiling Cython file:\n",
      "  \u001b[31m   \u001b[0m ------------------------------------------------------------\n",
      "  \u001b[31m   \u001b[0m ...\n",
      "  \u001b[31m   \u001b[0m         cdef SIZE_t start = self.start\n",
      "  \u001b[31m   \u001b[0m         cdef SIZE_t pos = self.pos\n",
      "  \u001b[31m   \u001b[0m         cdef SIZE_t end = self.end\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         cdef double* sum_left = self.sum_left\n",
      "  \u001b[31m   \u001b[0m         cdef double* sum_right = self.sum_right\n",
      "  \u001b[31m   \u001b[0m                                     ^\n",
      "  \u001b[31m   \u001b[0m ------------------------------------------------------------\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m causalml/inference/tree/causaltree.pyx:136:37: Cannot assign type 'double[::1]' to 'double *'\n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 2, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"<pip-setuptools-caller>\", line 34, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/vn/78yrfhs92slfj6nr61fhb9w00000gn/T/pip-install-kwbmvzdd/causalml_d42ece055c2d45bd91ed21dc74796834/setup.py\", line 71, in <module>\n",
      "  \u001b[31m   \u001b[0m     ext_modules=cythonize(extensions, annotate=True),\n",
      "  \u001b[31m   \u001b[0m   File \"/Users/jace/opt/anaconda3/envs/DL/causalml/lib/python3.10/site-packages/Cython/Build/Dependencies.py\", line 1127, in cythonize\n",
      "  \u001b[31m   \u001b[0m     cythonize_one(*args)\n",
      "  \u001b[31m   \u001b[0m   File \"/Users/jace/opt/anaconda3/envs/DL/causalml/lib/python3.10/site-packages/Cython/Build/Dependencies.py\", line 1250, in cythonize_one\n",
      "  \u001b[31m   \u001b[0m     raise CompileError(None, pyx_file)\n",
      "  \u001b[31m   \u001b[0m Cython.Compiler.Errors.CompileError: causalml/inference/tree/causaltree.pyx\n",
      "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n",
      "  \n",
      "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "\u001b[1;31merror\u001b[0m: \u001b[1mlegacy-install-failure\u001b[0m\n",
      "\n",
      "\u001b[31m×\u001b[0m Encountered error while trying to install package.\n",
      "\u001b[31m╰─>\u001b[0m causalml\n",
      "\n",
      "\u001b[1;35mnote\u001b[0m: This is an issue with the package mentioned above, not pip.\n",
      "\u001b[1;36mhint\u001b[0m: See above for output from the failure.\n",
      "\u001b[?25h"
     ]
    }
   ],
   "source": [
    "!pip install causalml"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "a3ebc899-1c8f-49a9-9d6f-8938b0861dc7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Package                       Version\n",
      "----------------------------- -----------\n",
      "anyio                         3.6.1\n",
      "appnope                       0.1.3\n",
      "argon2-cffi                   21.3.0\n",
      "argon2-cffi-bindings          21.2.0\n",
      "asttokens                     2.0.5\n",
      "attrs                         21.4.0\n",
      "Babel                         2.10.1\n",
      "backcall                      0.2.0\n",
      "backports.functools-lru-cache 1.6.4\n",
      "beautifulsoup4                4.11.1\n",
      "bleach                        5.0.0\n",
      "brotlipy                      0.7.0\n",
      "certifi                       2022.5.18.1\n",
      "cffi                          1.15.0\n",
      "charset-normalizer            2.0.12\n",
      "cloudpickle                   2.1.0\n",
      "cryptography                  37.0.2\n",
      "cycler                        0.11.0\n",
      "Cython                        0.29.30\n",
      "debugpy                       1.6.0\n",
      "decorator                     5.1.1\n",
      "defusedxml                    0.7.1\n",
      "dill                          0.3.5.1\n",
      "entrypoints                   0.4\n",
      "executing                     0.8.3\n",
      "fastjsonschema                2.15.3\n",
      "flit_core                     3.7.1\n",
      "fonttools                     4.33.3\n",
      "future                        0.18.2\n",
      "graphviz                      0.20\n",
      "idna                          3.3\n",
      "importlib-metadata            4.11.4\n",
      "importlib-resources           5.7.1\n",
      "ipykernel                     6.13.0\n",
      "ipython                       8.4.0\n",
      "ipython-genutils              0.2.0\n",
      "jedi                          0.18.1\n",
      "Jinja2                        3.1.2\n",
      "joblib                        1.1.0\n",
      "json5                         0.9.5\n",
      "jsonschema                    4.5.1\n",
      "jupyter-client                7.3.1\n",
      "jupyter-core                  4.10.0\n",
      "jupyter-lsp                   1.5.1\n",
      "jupyter-server                1.17.0\n",
      "jupyterlab                    3.4.2\n",
      "jupyterlab-lsp                3.10.1\n",
      "jupyterlab-pygments           0.2.2\n",
      "jupyterlab-server             2.14.0\n",
      "kiwisolver                    1.4.2\n",
      "lightgbm                      3.3.2\n",
      "llvmlite                      0.38.1\n",
      "MarkupSafe                    2.1.1\n",
      "matplotlib                    3.5.2\n",
      "matplotlib-inline             0.1.3\n",
      "mistune                       0.8.4\n",
      "nbclassic                     0.3.7\n",
      "nbclient                      0.6.3\n",
      "nbconvert                     6.5.0\n",
      "nbformat                      5.4.0\n",
      "nest-asyncio                  1.5.5\n",
      "notebook                      6.4.11\n",
      "notebook-shim                 0.1.0\n",
      "numba                         0.55.2\n",
      "numpy                         1.22.4\n",
      "opt-einsum                    3.3.0\n",
      "packaging                     21.3\n",
      "pandas                        1.4.2\n",
      "pandocfilters                 1.5.0\n",
      "parso                         0.8.3\n",
      "patsy                         0.5.2\n",
      "pexpect                       4.8.0\n",
      "pickleshare                   0.7.5\n",
      "Pillow                        9.1.1\n",
      "pip                           22.1.1\n",
      "progressbar2                  4.0.0\n",
      "prometheus-client             0.14.1\n",
      "prompt-toolkit                3.0.29\n",
      "psutil                        5.9.1\n",
      "ptyprocess                    0.7.0\n",
      "pure-eval                     0.2.2\n",
      "pycparser                     2.21\n",
      "pydotplus                     2.0.2\n",
      "pygam                         0.8.0\n",
      "Pygments                      2.12.0\n",
      "pyOpenSSL                     22.0.0\n",
      "pyparsing                     3.0.9\n",
      "pyro-api                      0.1.2\n",
      "pyro-ppl                      1.8.1\n",
      "pyrsistent                    0.18.1\n",
      "PySocks                       1.7.1\n",
      "python-dateutil               2.8.2\n",
      "python-utils                  3.3.1\n",
      "pytz                          2022.1\n",
      "pyzmq                         23.0.0\n",
      "requests                      2.27.1\n",
      "scikit-learn                  1.1.1\n",
      "scipy                         1.8.1\n",
      "seaborn                       0.11.2\n",
      "Send2Trash                    1.8.0\n",
      "setuptools                    62.3.2\n",
      "shap                          0.40.0\n",
      "six                           1.16.0\n",
      "slicer                        0.0.7\n",
      "sniffio                       1.2.0\n",
      "soupsieve                     2.3.1\n",
      "stack-data                    0.2.0\n",
      "statsmodels                   0.13.2\n",
      "terminado                     0.15.0\n",
      "threadpoolctl                 3.1.0\n",
      "tinycss2                      1.1.1\n",
      "torch                         1.11.0\n",
      "tornado                       6.1\n",
      "tqdm                          4.64.0\n",
      "traitlets                     5.2.1.post0\n",
      "typing_extensions             4.2.0\n",
      "urllib3                       1.26.9\n",
      "wcwidth                       0.2.5\n",
      "webencodings                  0.5.1\n",
      "websocket-client              1.3.2\n",
      "wheel                         0.37.1\n",
      "xgboost                       1.6.1\n",
      "zipp                          3.8.0\n"
     ]
    }
   ],
   "source": [
    "!pip list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "7d8d4976-ca79-4986-b803-b0d4fb09b069",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'causalml'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "Input \u001b[0;32mIn [1]\u001b[0m, in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mcausalml\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01minference\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mmeta\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m BasesRegressor \n\u001b[1;32m      2\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mxgboost\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m XGBRegressor\n",
      "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'causalml'"
     ]
    }
   ],
   "source": [
    "from causalml.inference.meta import BasesRegressor \n",
    "from xgboost import XGBRegressor"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "39bbfacf-0d51-4115-ae95-2d233d08a6ac",
   "metadata": {},
   "outputs": [],
   "source": [
    "y,X,treatment,_,_,e synthetic_data(mode=1,n=N_SAMPLES,p=N_FEATURES)\n",
    "X_multi np.array(['treatment_A'if x 1 else 'control'for x in treatment])\n",
    "learner_s BaseSRegressor(learner=XGBRegressor())\n",
    "cate_s learner_s.fit_predict(X=X,treatment=treatment,y=y)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
